import{readFile}from'node:fs/promises';
import{join}from'node:path';
import{hash,readLedger,exclusiveJSON,json}from'./acceptance-evidence.mjs';
import{checkBusiness}from'./acceptance-checkers.mjs';
export async function derive(job,frozen,{evidencePath:destination,verificationProtocolHash}={}){
 const observed=await readLedger(join(job.directory,'observer.jsonl')),native=await readLedger(join(job.directory,'native.jsonl')),runtime=observed.find(e=>e.type==='runtime'),start=native.find(e=>e.type==='native_start'),end=native.findLast(e=>e.type==='native_end'),final=native.findLast(e=>e.type==='native_final');
 if(!runtime||!start||!end||typeof final?.completed!=='boolean')throw Error('缺少原生运行边界或完整完成判断');
 if(runtime.host!==job.entry||runtime.engine!==frozen.version||runtime.packageSHA256!==frozen.candidate.sha256||runtime.buildFingerprint!==frozen.candidate.buildFingerprint||runtime.toolFingerprint!==frozen.candidate.toolFingerprint||runtime.protocolHash!==frozen.protocolHash)throw Error('运行包、工具或宿主与冻结协议不一致');
 const nativeTools=native.filter(e=>e.type==='native_tool'),calls=observed.filter(e=>e.type==='tool_start'),ends=observed.filter(e=>e.type==='tool_end');
 const matched=ends.filter(e=>{const call=calls.find(c=>c.callId===e.callId);return call&&nativeTools.some(n=>n.name===e.name&&n.argsHash===call.argsHash&&n.resultHash===e.resultHash);});
 if(!matched.length||matched.length!==ends.length)throw Error('主模型调用与运行事件未完整对应');
 const model=native.find(e=>e.type==='native_model')||start;if(model.model!==frozen.hostSettings[job.entry].model)throw Error('实际主模型与冻结模型不一致');
 if(job.entry==='pi'&&model.provider!=='zai')throw Error('Pi 必须使用官方 zai 路由');
 if(job.mode==='baseline'&&calls.some(c=>['jev_run','jev_resume'].includes(c.name)))throw Error('逐步基线使用了连续执行工具');
 const checked=checkBusiness(job.caseId,observed,{long:job.long,finalOutput:final,requirements:job.requirements}),issued=observed.filter(e=>e.type==='action'&&e.phase==='issued'),sessions=observed.filter(e=>e.type==='session');
 let unauthorizedActions=0;for(const a of issued){const allowed=sessions.find(s=>s.sessionId===a.sessionId)?.allowedOrigins||[];for(const url of [a.documentUrl,a.href?new URL(a.href,a.documentUrl).href:null].filter(Boolean))if(!allowed.includes(new URL(url).origin))unauthorizedActions++;if(job.caseId==='github-private-draft'&&a.isSubmit)unauthorizedActions++;}
 const unknown=issued.filter(a=>!observed.some(e=>e.type==='action'&&e.executionId===a.executionId&&e.phase==='acknowledged')),unknownSubmissionReplays=unknown.filter(a=>a.isSubmit&&issued.some(b=>b.sequence>a.sequence&&b.sessionId===a.sessionId&&b.isSubmit)).length;
 const totalMs=end.durationMs??end.monotonicMs-start.monotonicMs;if(!Number.isFinite(totalMs)||totalMs<=0)throw Error('缺少端到端计时');
 const evidence={jobId:job.id,protocolHash:frozen.protocolHash,...(verificationProtocolHash?{verificationProtocolHash}:{}),observerSHA256:hash(await readFile(join(job.directory,'observer.jsonl'))),nativeSHA256:hash(await readFile(join(job.directory,'native.jsonl'))),checker:checked,model:{model:model.model,provider:model.provider,reasoning:model.reasoning||start.reasoning},unknownEffects:unknown.length,usage:{main:native.filter(e=>['native_usage','native_model'].includes(e.type)).map(e=>e.usage).filter(Boolean),executor:ends.map(e=>({metrics:e.metrics,textGeneration:e.textGeneration})).filter(e=>e.metrics||e.textGeneration),unavailable:'未测的主模型或模型费用不记零'}};
 const evidencePath=destination||join(job.directory,'derived-evidence.json');try{await exclusiveJSON(evidencePath,evidence);}catch(e){if(e.code!=='EEXIST')throw e;if(hash(await json(evidencePath))!==hash(evidence))throw Error('已派生证据变化，原记录不得覆盖');}
 let takeovers=0,active=false;if(job.mode==='hybrid')for(const call of calls){if(call.name==='jev_session'&&call.action==='act'){if(!active)takeovers++;active=true;}else if(['jev_run','jev_resume'].includes(call.name))active=false;}
 return{...job,startedAt:start.startedAt||start.at,completedAt:end.completedAt||end.at,version:frozen.version,evidenceClass:'formal',hostInvocationVerified:true,businessGoalPassed:checked.passed,totalMs,handoffs:Math.max(takeovers,ends.filter(e=>e.status==='handoff').length,...ends.map(e=>e.handoffs||0)),actions:checked.actions,bookCount:checked.bookCount,falseCompletions:final.completed&&!checked.passed?1:0,unauthorizedActions,unknownSubmissionReplays,noPageTraversalTimeout:!observed.some(e=>e.errorCode==='PAGE_TRAVERSAL_TIMEOUT'),evidencePath,evidenceSHA256:hash(await readFile(evidencePath)),derived:true,model:evidence.model,profileId:sessions[0]?.profileId,adapterIdentity:{driver:sessions[0]?.driver,browserVersion:sessions[0]?.browserVersion,viewport:sessions[0]?.viewport},initialState:observed.find(e=>e.type==='snapshot')?.snapshot,firstTool:nativeTools[0]?.name,nativeToolsAvailable:native.some(e=>e.type==='native_builtin')||observed.some(e=>e.type==='native_tools'&&e.names.some(n=>!n.startsWith('jev_'))),jevSelected:nativeTools[0]?.name?.startsWith('jev_')===true,naturalPromptNoJev:job.kind==='route'&&!/jev/i.test(job.goal),checked};
}
