import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
import {runCommand} from '../src/platform.mjs';

const pkg=JSON.parse(await readFile('package.json','utf8'));
runCommand(process.execPath,['scripts/scan-secrets.mjs','--history']);
await mkdir('dist',{recursive:true});
const packed=JSON.parse(runCommand('npm',['pack','--json','--ignore-scripts','--pack-destination','dist'],{stdio:'pipe'}).stdout.toString())[0];
const names=packed.files.map(f=>f.path);
for(const required of ['src/cli.mjs','scripts/linux-sandbox.mjs','integrations/pi/index.ts','skills/jev-browser/SKILL.md','plugin.json','mcp.json','README.md','README.en.md','LICENSE','NOTICE','npm-shrinkwrap.json'])if(!names.includes(required))throw Error(`安装包缺少 ${required}`);
const forbidden=names.filter(name=>/(?:^|\/)(?:node_modules|artifacts|\.git|\.env(?:\..*)?|config\.json|credentials\.env|profiles|private-backups)(?:\/|$)/.test(name));
if(forbidden.length)throw Error('安装包包含私密或运行时目录');
const archive=join('dist',packed.filename);
runCommand(process.execPath,['scripts/scan-secrets.mjs','--archive',archive]);
const hash=createHash('sha256').update(await readFile(archive)).digest('hex');
const manifest={name:pkg.name,version:pkg.version,status:'RC',protocol:2,entries:['gpt','pi','mcp'],node:pkg.engines.node,archive:packed.filename,sha256:hash,files:names};
await writeFile('dist/release-manifest.json',JSON.stringify(manifest,null,2)+'\n');
await writeFile('dist/SHA256SUMS',`${hash}  ${packed.filename}\n`);
console.log(JSON.stringify({version:pkg.version,archive:packed.filename,files:names.length,bytes:packed.size,sha256:hash}));
