import {verifyGutenbergDetails} from './business-verifiers.mjs';
const gt='https://www.gutenberg.org',wiki='https://en.wikipedia.org',gh='https://github.com';
const evidence=steps=>steps.map(s=>({kind:'evidence',subgoal:s.id}));
const formats='#download a.read-online-button,#download a.featured-format-link,#download a.other-format-link';
export const publicCases=[
  {id:'wiki-fields',url:wiki+'/wiki/Main_Page',goal:'在 Wikipedia 搜索 Alan Turing，采集条目标题、出生信息、教育信息、贡献字段和来源 URL',steps:[
    {id:'input',goal:'填写搜索词 Alan Turing',value:'Alan Turing',checks:[{kind:'field',label:'Search Wikipedia',equals:'Alan Turing'}]},
    {id:'topic',goal:'提交搜索，进入 Alan Turing 条目，采集标题与信息框字段',checks:[{kind:'url',equals:wiki+'/wiki/Alan_Turing'},{kind:'elementText',selector:'#firstHeading',equals:'Alan Turing'}],extract:[{name:'title',selector:'#firstHeading'},{name:'fields',selector:'.infobox tr',all:true,maxItems:30,maxChars:500,required:false}]}],verify:r=>r.data?.topic?.data.title==='Alan Turing'&&['Born','Education','Known for'].every(x=>r.data.topic.data.fields.some((row,i)=>row.startsWith(x)&&row.slice(x.length).trim()&&!r.data.topic.coverage.fields.items[i].truncated))},
  {id:'wiki-section',url:wiki+'/wiki/Alan_Turing',goal:'通过条目目录定位 Death 章节，采集章节标题、首段及来源 URL',steps:[
    {id:'section',goal:'通过目录点击 Death 章节，读取该章节首段和来源',checks:[{kind:'url',equals:wiki+'/wiki/Alan_Turing#Death'},{kind:'elementText',selector:'#Death',equals:'Death'}],extract:[{name:'heading',selector:'#Death'},{name:'paragraph',source:'section',selector:'#Death',maxParagraphs:1,maxChars:3000}]}],verify:r=>r.data?.section?.data.heading==='Death'&&!!r.data.section.data.paragraph?.trim()&&r.data.section.coverage.paragraph.paragraphs===1&&r.data.section.coverage.paragraph.truncated===false},
  {id:'gutenberg-author',url:gt+'/',goal:'搜索 Charles Dickens，按搜索结果顺序核查前三本书的详情和可用阅读格式；缺项记录不替换',steps:[
    {id:'input',goal:'填写作者 Charles Dickens',value:'Charles Dickens',checks:[{kind:'field',label:'Search books',equals:'Charles Dickens'}]},
    {id:'discover',goal:'提交作者搜索，采集搜索结果前三本书的标题和链接',checks:[{kind:'url',includes:'/ebooks/search/'},{kind:'title',includes:'Charles Dickens'},{kind:'count',selector:'.booklink',minCount:3}],extract:[{name:'titles',selector:'.booklink .title',all:true,maxItems:3},{name:'links',selector:'.booklink a.link',attribute:'href',all:true,maxItems:3}]},
    ...Array.from({length:3},(_,i)=>[
      {id:`detail-${i}`,goal:`打开本次搜索结果第 ${i+1} 本书的详情；目标 URL 以 pendingRequirements 为准；采集详情和可用阅读格式`,checks:[{kind:'url',equalsFrom:{subgoal:'discover',field:'links',index:i,resolveUrl:true}},{kind:'exists',selector:'table.bibrec'},{kind:'elementText',selector:'h1',notEmpty:true}],extract:[{name:'title',selector:'h1'},{name:'metadata',selector:'table.bibrec tr',all:true,maxItems:30,maxChars:1000},{name:'formatLabels',selector:formats,all:true,maxItems:40,required:false},{name:'formatLinks',selector:formats,attribute:'href',all:true,maxItems:40,required:false}]},
      {id:`return-${i}`,goal:'通过浏览器返回本次作者搜索结果页',allowedKinds:['back'],checks:[{kind:'url',equalsFrom:{subgoal:'discover',source:'url'}}]}
    ]).flat()],verify:r=>verifyGutenbergDetails(r,{count:3}).passed&&r.url===r.data.discover.url},
  {id:'gutenberg-ranking',url:gt+'/',goal:'读取现场昨天下载榜单的前十本书，采集标题与下载次数，随后由主 Agent 的代码排序',steps:[
    {id:'ranking',goal:'打开 Frequently Downloaded 下载榜单，采集昨天榜单前十项的原始文字和来源',checks:[{kind:'url',includes:'/browse/scores/top'},{kind:'exists',selector:'#books-last1 + ol li:nth-child(10)'}],extract:[{name:'rows',selector:'#books-last1 + ol li a',all:true,maxItems:10},{name:'links',selector:'#books-last1 + ol li a',attribute:'href',all:true,maxItems:10}]}],verify:r=>r.data?.ranking?.data.rows.length===10&&r.data.ranking.data.links.length===10&&new Set(r.data.ranking.data.links).size===10&&r.data.ranking.data.links.every(href=>/^\/ebooks\/\d+$/.test(href)),postprocess:r=>r.data.ranking.data.rows.map((text,i)=>({title:text.replace(/\s*\(\d+\)\s*$/,''),downloads:Number(text.match(/\((\d+)\)\s*$/)?.[1]),url:new URL(r.data.ranking.data.links[i],r.data.ranking.url).href})).sort((a,b)=>b.downloads-a.downloads)},
  {id:'github-public',url:gh+'/browser-use/jev-ultrafast',goal:'读取 browser-use/jev-ultrafast 的 README 前 1500 字、完整许可证和两者的来源 URL',steps:[
    {id:'readme',goal:'读取仓库 README 的前1500字，并发现 LICENSE 文件链接',checks:[{kind:'url',equals:gh+'/browser-use/jev-ultrafast'},{kind:'exists',selector:'article.markdown-body'}],extract:[{name:'readme',selector:'article.markdown-body',maxChars:1500},{name:'licenseLinks',selector:'a[href*="/blob/"][href$="LICENSE"]',attribute:'href',all:true,maxItems:2}]},
    {id:'license',goal:'打开本次观测到的 LICENSE 文件，读取完整许可证和来源',checks:[{kind:'url',equalsFrom:{subgoal:'readme',field:'licenseLinks',index:0,resolveUrl:true}},{kind:'text',selector:'.react-code-lines',includes:'MIT License'}],extract:[{name:'license',selector:'.react-code-lines',maxChars:5000}]}],verify:r=>typeof r.data?.readme?.data.readme==='string'&&r.data.readme.data.readme.length>0&&r.data.readme.data.readme.length<=1500&&(!r.data.readme.coverage.readme.items[0].truncated||r.data.readme.data.readme.length===1500)&&r.data?.license?.data.license.includes('THE SOFTWARE IS PROVIDED')&&r.data.license.data.license.includes('OTHER DEALINGS IN THE SOFTWARE.')&&!r.data.license.coverage.license.items[0].truncated}
];
export const makeTask=(scenario,sessionId,requestId)=>({sessionId,requestId,goal:scenario.goal,inputs:Object.fromEntries(scenario.steps.flatMap(step=>step.checks.filter(c=>c.kind==='field'&&c.label&&step.value!==undefined).map(c=>[c.label,step.value]))),allowedOrigins:[new URL(scenario.url).origin],subgoals:scenario.steps,completionChecks:evidence(scenario.steps)});
