import {z} from 'zod';

const dataRef=z.union([
  z.object({subgoal:z.string().min(1),field:z.string().min(1),index:z.number().int().min(0).optional(),resolveUrl:z.boolean().optional()}).strict(),
  z.object({subgoal:z.string().min(1),source:z.literal('url'),resolveUrl:z.boolean().optional()}).strict()
]).describe('引用采集字段时用 field，可加 index 和 resolveUrl；引用阶段页面地址时用 source:"url"。field 与 source 互斥，页面地址不能加 index。');
const id=z.string().min(1).max(100).regex(/^[A-Za-z0-9_-]+$/).describe('仅字母、数字、下划线和连字符，最多100字符；不要用冒号、斜杠或空格');
const check=z.object({kind:z.enum(['url','title','text','exists','field','checked','selected','elementText','attribute','count','evidence']),equalsFrom:dataRef.optional(),includesFrom:dataRef.optional(),selector:z.string().describe('标准 DOM CSS 选择器；不支持 Playwright 的 :has-text()、text= 或 jQuery 的 :contains()。先检查当前页面，使用新鲜观测的 selector；文本条件用 includes/label 或 section。').optional(),label:z.string().optional(),labelIncludes:z.string().optional(),equals:z.union([z.string(),z.boolean()]).optional(),includes:z.string().optional(),excludes:z.string().optional(),notEmpty:z.boolean().optional(),maxLength:z.number().int().positive().optional(),minCount:z.number().int().min(0).optional(),maxCount:z.number().int().min(0).optional(),attribute:z.string().optional(),frame:z.string().optional(),subgoal:z.string().optional(),sensitive:z.boolean().optional()});
const stageCheck=check.extend({kind:z.enum(check.shape.kind.options.filter(kind=>kind!=='evidence'))});
export const verificationChecksSchema=z.array(stageCheck).min(1).max(30).refine(checks=>checks.every(c=>!c.equalsFrom&&!c.includesFrom&&(c.kind==='exists'||c.kind==='count'&&(c.minCount!==undefined||c.maxCount!==undefined)||c.equals!==undefined||c.includes!==undefined||c.excludes!==undefined||c.notEmpty===true)),'动作核验需要明确的实际页面后置条件，不接受阶段引用或空条件');
const extract=z.object({name:z.string(),required:z.boolean().optional(),source:z.enum(['url','title','section']).describe('url/title读取页面来源或标题；section读取某标题后的正文段落。提取DOM元素文本或链接href时不设source，只设selector及可选attribute/all。').optional(),selector:z.string().describe('标准 DOM CSS 选择器；不支持 Playwright 的 :has-text()、text= 或 jQuery 的 :contains()。先检查当前页面，使用新鲜观测的 selector；文本条件用 includes/label 或 section。').optional(),attribute:z.string().optional(),all:z.boolean().optional(),maxItems:z.number().int().min(1).max(100).optional(),maxParagraphs:z.number().int().min(1).max(10).optional(),maxChars:z.number().int().min(1).max(5000).optional()});
export const taskSchema=z.object({sessionId:id,requestId:id,goal:z.string().min(1).describe('必填：保留用户完整原始业务要求，不能省略或只写局部阶段'),inputs:z.record(z.string(),z.union([z.string(),z.boolean(),z.number()])).optional(),allowedOrigins:z.array(z.string()).min(1),subgoals:z.array(z.object({id:id,goal:z.string(),checks:z.array(stageCheck).min(1),value:z.string().optional(),checked:z.boolean().optional(),generate:z.string().optional(),hostOnly:z.boolean().optional(),sensitive:z.boolean().optional(),allowSubmit:z.boolean().optional(),allowedKinds:z.array(z.enum(['click','fill','press','check','select','scroll','wait','back'])).optional(),extract:z.array(extract).optional()})).min(1),completionChecks:z.array(check).min(1),budget:z.object({maxDurationMs:z.number().positive().max(900000).optional(),maxActions:z.number().int().positive().max(200).optional(),sliceMs:z.number().positive().max(45000).optional()}).optional()});

export const instructions='需要网页交互时优先使用 jev_session 和 jev_run。主 Agent 负责完整目标、来源授权、完成条件和接管核验。需要登录态时先 list/profiles 检查同一宿主的已有会话和档案，用 useProfile 选择已有档案；不要为每次任务另建空档案或重复要求登录。登录由用户本人完成。若返回 running，用 jev_resume 继续；handoff 时先检查同一现场，再使用新鲜 ref 接管并续跑。verified 必须检查原始要求与阶段证据。保留宿主原生工具；独立浏览器成绩不称为内置侧栏成绩。';
export const toolDefinitions=[
  {name:'jev_session',title:'Jev 浏览器会话',description:'open复用持久档案；profiles返回实际版本、构建指纹与宿主，useProfile选择已有档案。inspect提供新鲜ref；act执行单个动作，已知值用value，新文字可用generate调用文本模型，二者互斥。verifyAction用sessionId、actionId和明确checks只核验已发出动作，不能执行或重放；verified只表示该动作，不等于任务完成。close保留档案和登录态。',schema:z.object({action:z.enum(['open','list','profiles','useProfile','inspect','act','verifyAction','close']),sessionId:z.string().optional(),profileId:z.string().optional(),actionId:z.string().optional(),checks:verificationChecksSchema.optional(),url:z.string().optional(),allowedOrigins:z.array(z.string()).optional(),headless:z.boolean().optional(),label:z.string().optional(),ref:z.string().optional(),value:z.union([z.string(),z.boolean()]).optional(),generate:z.string().min(1).max(2000).optional(),authorizedSubmit:z.boolean().optional(),runId:z.string().optional(),cursor:z.object({documentId:z.string(),url:z.string(),selector:z.string().describe('标准 DOM CSS 选择器；不支持 Playwright 的 :has-text()、text= 或 jQuery 的 :contains()。先检查当前页面，使用新鲜观测的 selector；文本条件用 includes/label 或 section。').optional(),frameIndex:z.number().optional()}).optional()}).refine(a=>a.generate===undefined||a.value===undefined,'明确值与新文字生成不能混用')},
  {name:'jev_run',title:'Jev 连续执行',description:'连续执行最多45秒。task必须包含sessionId、requestId、goal、allowedOrigins、subgoals和completionChecks。requestId用当前sessionId加阶段标识组成；任务变更需新编号，同编号不得绑定不同任务。每个subgoal必须有id、goal、checks；检查格式为{kind:"url",includes:"路径"}等；完成检查为{kind:"evidence",subgoal:"阶段id"}。已知填写值放该阶段value，或以观测字段标签为键放task.inputs；新文字用generate。不要传action、type、url、description等未声明的阶段字段。默认总预算90秒/40动作；长任务最多15分钟/200动作。',schema:z.object({task:taskSchema})},
  {name:'jev_resume',title:'Jev 原现场续跑',description:'从本机检查点继续；先核对未知动作的实际效果，绝不直接重放。重启后原登录档案打开并检查现场，才可显式 reattach。',schema:z.object({runId:z.string(),reattach:z.boolean().optional()})},
  {name:'jev_status',title:'Jev 任务进度',description:'返回完成与剩余阶段、接管原因、结构化采集数据、来源证据、累计耗时与版本。不返回大体积检查点。',schema:z.object({runId:z.string()}),readOnly:true},
  {name:'jev_cancel',title:'Jev 取消任务',description:'取消后停止发起新动作，保留已发出但效果未知的动作，供检查与恢复。',schema:z.object({runId:z.string()})}
];
export const toolJSONSchema=definition=>z.toJSONSchema(definition.schema,{target:'draft-7'});
